name: Initialise Repo

on:
  [workflow_dispatch]

permissions:
  issues: write 
  contents: write

jobs:
  run-script:
    name: run-script
    runs-on: ubuntu-latest

    steps:
    - name: Create a new issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Homepage",
          "body": "This is an automated issue created by the workflow."
        }'
        
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Profile Page",
          "body": "This is an automated issue created by the workflow."
        }'
        
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Register & Login",
          "body": "This is an automated issue created by the workflow."
        }'

         curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Add Recipes Pages",
          "body": "This is an automated issue created by the workflow."
        }'

         curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Recipes Page & Search",
          "body": "This is an automated issue created by the workflow."
        }'
